# Generated by Django 5.1.5 on 2025-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_photo_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(null=True, upload_to="photos/"),
        ),
    ]
