# Common
README.md
CHANGELOG.md
docker-compose.yml
Dockerfile
Dockerfile.dockerignore
.DS_Store

# git
.git
.gitattributes
.gitignore

# JetBrains
.idea

# Node
## Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

## Dependency directories
node_modules/
