services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
        -   .env
        volumes:
        -   static_volume:/usr/local/src/app/static
        depends_on:
        -   db
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_API_URL: ${VITE_API_URL}
        env_file:
        -   .env
        ports:
        -   "80:80"
        volumes:
        -   static_volume:/usr/local/src/app/static
        -   ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        -   backend
        restart: unless-stopped

    db:
        image: postgres:17
        env_file:
        -   .env
        volumes:
        -   postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
    static_volume:
