name: shared_memories

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: mhooker/shared_memories-backend:latest
        env_file:
        -   .env
        volumes:
        -   .env:/usr/local/src/.env:ro
        -   static_volume:/usr/local/src/app/static
        -   media_volume:/usr/local/src/app/media
        depends_on:
        -   db
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_API_URL: ${VITE_API_URL}
        image: mhooker/shared_memories-frontend:latest
        env_file:
        -   .env
        ports:
        -   "80:80"
        volumes:
        -   static_volume:/usr/local/src/app/static
        -   media_volume:/usr/local/src/app/media
        -   ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        -   backend
        restart: unless-stopped

    db:
        image: postgres:17.3-alpine
        env_file:
        -   .env
        volumes:
        -   postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
    static_volume:
    media_volume:
