# Generated by Django 5.1.5 on 2025-01-29 00:23

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(default='')),
                ('access_code', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(default='', max_length=40)),
                ('original_file_name', models.CharField(default='', max_length=255)),
                ('file_key', models.CharField(default='', max_length=512)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.event')),
            ],
        ),
    ]
