openapi: 3.0.3
info:
  title: Shared Memories REST API
  description: |
    This is the API for Shared Memories, an application for sharing photos from events. The API allows event organizers to create events and attendees to upload photos, which are displayed based on their EXIF timestamp.
  version: 0.1.0
  contact:
    email: sharedmemoriessupport@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/license/mit/'
servers:
  - url: http://localhost:8000/api/
tags:
  - name: items
    description: Manage items
  - name: events
    description: Manage events
  - name: photos
    description: Upload and retrieve photos
  - name: gallery
    description: Retrieve event information and photos
paths:
  /items:
    get:
      tags:
        - items
      summary: Retrieve all items
      description: Retrieve a list of all items.
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/item'
              examples:
                example1:
                  summary: Example with two items
                  value:
                    - id: 1
                      name: "Staff"
                      description: "Versatile weapon, deals 1d6 bludgeoning damage or 1d8 when wielded two-handed."
                    - id: 2
                      name: "Spells"
                      description: "The Wizard’s most important tool for learning and preparing spells."
  /events:
    get:
      tags:
        - events
      summary: Retrieve all events
      description: Retrieve a list of all events created by organizers.
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/event'
              examples:
                example1:
                  summary: Example with two events
                  value:
                    - id: 1
                      title: "Marryland Day 2023"
                      description: "Enjoy a day of learning and discovery at the University of Maryland’s springtime open house. Join us for interactive demonstrations, performances and workshops showcasing science and tech, the arts, sports, agriculture and more!"
                      date: "2023-04-29"
                      access_code: "abc123"
                    - id: 2
                      title: "Maryland Day 2024"
                      description: "Enjoy a day of learning and discovery at the University of Maryland’s springtime open house. Join us for interactive demonstrations, performances and workshops showcasing science and tech, the arts, sports, agriculture and more!"
                      date: "2024-04-27"
                      access_code: "def456"
    post:
      tags:
        - events
      summary: Create a new event
      description: Organizers can create a new event.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
        '400':
          description: Invalid input
  /events/{event_id}:
    get:
      tags:
        - events
      summary: Retrieve an event by ID
      description: Retrieve details of a specific event using its ID.
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Event details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
        '404':
          description: Event not found
    delete:
      tags:
        - events
      summary: Delete an event
      description: Delete an event using its ID.
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found
  /events/{event_id}/photos:
    get:
      tags:
        - photos
      summary: Retrieve photos for an event
      description: Retrieve all photos for an event, ordered based on their EXIF timestamp.
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of photos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/photo'
              examples:
                example1:
                  summary: List with three photos.
                  value:
                    - id: 1
                      event_id: 1
                      uploaded_by: "Michael"
                      original_file_name: "DSCF9344.jpg"
                      upload_timestamp: "2025-01-26T18:11:13.390Z"
                    - id: 2
                      event_id: 1
                      uploaded_by: "Michael"
                      original_file_name: "DSCF9348.jpg"
                      upload_timestamp: "2025-01-26T18:29:43.990Z"
                    - id: 3
                      event_id: 1
                      uploaded_by: "Michael"
                      original_file_name: "DSCF9351.jpg"
                      upload_timestamp: "2025-01-26T18:30:24.110Z"
  /photos:
    post:
      tags:
        - photos
      summary: Upload a photo to an event
      description: Upload a photo to a specific event. Photos are displayed based on their EXIF timestamp.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                  format: int64
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Photo uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/photo'
        '400':
          description: Invalid input
  /gallery/{access_code}:
    get:
      tags:
        - gallery
      summary: Retrieve a gallery by access code
      description: Retrieve event information and photos of a specific event using its access code.
      parameters:
        - name: access_code
          in: path
          required: true
          schema:
            type: string
            format: int32
            maxLength: 6
      responses:
        '200':
          description: Event details and list of photos retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gallery'
        '404':
          description: Gallery with access code not found
components:
  schemas:
    item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 6
        description:
          type: string
      example:
        id: 1
        title: "Staff"
        description: "Versatile weapon, deals 1d6 bludgeoning damage or 1d8 when wielded two-handed."
    event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        access_code:
          type: string
      example:
        id: 1
        title: "Maryland Day 2023"
        description: "Enjoy a day of learning and discovery at the University of Maryland’s springtime open house. Join us for interactive demonstrations, performances and workshops showcasing science and tech, the arts, sports, agriculture and more! "
        date: "2023-04-29"
        access_code: "abc123"
    photo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        event_id:
          type: integer
          format: int64
        uploaded_by:
          type: string
        original_file_name:
          type: string
        upload_timestamp:
          type: string
          format: date-time
      example:
        id: 1
        event_id: 1
        uploaded_by: "Michael"
        original_file_name: "DSCF9344.jpg"
        upload_timestamp: "2025-01-26T18:11:13.390Z"
    gallery:
      type: object
      properties:
        event_title:
          type: string
        event_date:
          type: string
          format: date
        event_description:
          type: string
        event_photos:
          type: array
          items:
            $ref: '#/components/schemas/photo'
